"""Khoi tao bang: linh_vuc, don_vi, nguoi_dung, tai_lieu

Revision ID: 004cec467c98
Revises: 
Create Date: 2026-07-21 08:05:11.013913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004cec467c98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('don_vi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten')
    )
    op.create_table('linh_vuc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten')
    )
    op.create_table('nguoi_dung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_dang_nhap', sa.String(length=100), nullable=False),
    sa.Column('mat_khau_hash', sa.String(length=255), nullable=False),
    sa.Column('ho_ten', sa.String(length=255), nullable=False),
    sa.Column('don_vi_id', sa.Integer(), nullable=True),
    sa.Column('vai_tro', sa.String(length=20), nullable=False),
    sa.Column('dang_hoat_dong', sa.Boolean(), nullable=False),
    sa.CheckConstraint("vai_tro IN ('admin', 'bien_tap', 'tra_cuu')", name='ck_nguoi_dung_vai_tro'),
    sa.ForeignKeyConstraint(['don_vi_id'], ['don_vi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_dang_nhap')
    )
    op.create_table('tai_lieu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tieu_de', sa.String(length=500), nullable=False),
    sa.Column('so_hieu', sa.String(length=100), nullable=True),
    sa.Column('linh_vuc_id', sa.Integer(), nullable=True),
    sa.Column('don_vi_id', sa.Integer(), nullable=True),
    sa.Column('loai_van_ban', sa.String(length=50), nullable=True),
    sa.Column('tinh_trang', sa.String(length=50), nullable=True),
    sa.Column('ngay_ban_hanh', sa.Date(), nullable=True),
    sa.Column('ngay_het_hieu_luc', sa.Date(), nullable=True),
    sa.Column('phien_ban', sa.String(length=20), nullable=True),
    sa.Column('duong_dan_file', sa.String(length=1000), nullable=True),
    sa.Column('noi_dung_text', sa.Text(), nullable=True),
    sa.Column('ngay_nap', sa.DateTime(), nullable=False),
    sa.Column('nguoi_nap_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['don_vi_id'], ['don_vi.id'], ),
    sa.ForeignKeyConstraint(['linh_vuc_id'], ['linh_vuc.id'], ),
    sa.ForeignKeyConstraint(['nguoi_nap_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tai_lieu')
    op.drop_table('nguoi_dung')
    op.drop_table('linh_vuc')
    op.drop_table('don_vi')
    # ### end Alembic commands ###
