"""them cot da_an xoa mem tai lieu

Revision ID: 58119c967811
Revises: 72de091b0f06
Create Date: 2026-07-28 14:42:18.320442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58119c967811'
down_revision = '72de091b0f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tai_lieu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('da_an', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tai_lieu', schema=None) as batch_op:
        batch_op.drop_column('da_an')

    # ### end Alembic commands ###
