"""Them cot tim kiem toan van noi_dung_tsv

Revision ID: 5b86789c4290
Revises: e0b4cbae184f
Create Date: 2026-07-21 10:59:47.989325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b86789c4290'
down_revision = 'e0b4cbae184f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tai_lieu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('noi_dung_tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('simple', coalesce(tieu_de, '')), 'A') || setweight(to_tsvector('simple', coalesce(so_hieu, '')), 'B') || setweight(to_tsvector('simple', coalesce(noi_dung_text, '')), 'C')", persisted=True), nullable=True))
        batch_op.create_index('ix_tai_lieu_noi_dung_tsv', ['noi_dung_tsv'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tai_lieu', schema=None) as batch_op:
        batch_op.drop_index('ix_tai_lieu_noi_dung_tsv', postgresql_using='gin')
        batch_op.drop_column('noi_dung_tsv')

    # ### end Alembic commands ###
