"""them bang thong bao va cot luot xem tai lieu

Revision ID: 5d79e0a61825
Revises: 8dcba30c438c
Create Date: 2026-07-22 15:15:30.796556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d79e0a61825'
down_revision = '8dcba30c438c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thong_bao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tieu_de', sa.String(length=500), nullable=False),
    sa.Column('tai_lieu_id', sa.Integer(), nullable=True),
    sa.Column('ngay_dang', sa.DateTime(), nullable=False),
    sa.Column('nguoi_dang_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nguoi_dang_id'], ['nguoi_dung.id'], ),
    sa.ForeignKeyConstraint(['tai_lieu_id'], ['tai_lieu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tai_lieu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('luot_xem', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tai_lieu', schema=None) as batch_op:
        batch_op.drop_column('luot_xem')

    op.drop_table('thong_bao')
    # ### end Alembic commands ###
