"""them cot tom tat tai lieu

Revision ID: 72de091b0f06
Revises: dd20213a4db2
Create Date: 2026-07-28 14:19:54.500774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72de091b0f06'
down_revision = 'dd20213a4db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tai_lieu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tom_tat', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tai_lieu', schema=None) as batch_op:
        batch_op.drop_column('tom_tat')

    # ### end Alembic commands ###
