"""them bang tep_tai_lieu, bo cot duong_dan_file khoi tai_lieu

Revision ID: 8dcba30c438c
Revises: 5b86789c4290
Create Date: 2026-07-22 14:18:39.973813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcba30c438c'
down_revision = '5b86789c4290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tep_tai_lieu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tai_lieu_id', sa.Integer(), nullable=False),
    sa.Column('duong_dan_file', sa.String(length=1000), nullable=False),
    sa.Column('thu_tu', sa.Integer(), nullable=False),
    sa.Column('noi_dung_text', sa.Text(), nullable=True),
    sa.Column('trang_thai_xu_ly', sa.String(length=20), nullable=False),
    sa.Column('ngay_them', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tai_lieu_id'], ['tai_lieu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tep_tai_lieu_tai_lieu_id'), 'tep_tai_lieu', ['tai_lieu_id'], unique=False)

    # Di chuyển dữ liệu file hiện có (1 tài liệu = 1 file trước đây) sang bảng file con mới,
    # trước khi bỏ cột duong_dan_file khỏi tai_lieu - không được mất dữ liệu file đã nạp.
    op.execute("""
        INSERT INTO tep_tai_lieu (tai_lieu_id, duong_dan_file, thu_tu, noi_dung_text, trang_thai_xu_ly, ngay_them)
        SELECT id, duong_dan_file, 0, noi_dung_text, trang_thai_xu_ly, ngay_nap
        FROM tai_lieu
        WHERE duong_dan_file IS NOT NULL
    """)

    with op.batch_alter_table('tai_lieu', schema=None) as batch_op:
        batch_op.drop_column('duong_dan_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tai_lieu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duong_dan_file', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))

    # Khôi phục cột duong_dan_file từ file đầu tiên (thu_tu nhỏ nhất) của mỗi tài liệu -
    # nếu tài liệu có nhiều file, các file còn lại sẽ mất khi hạ cấp (chấp nhận được vì
    # downgrade chỉ dùng khi cần lùi lại, không phải luồng vận hành bình thường).
    op.execute("""
        UPDATE tai_lieu
        SET duong_dan_file = tep.duong_dan_file
        FROM (
            SELECT DISTINCT ON (tai_lieu_id) tai_lieu_id, duong_dan_file
            FROM tep_tai_lieu
            ORDER BY tai_lieu_id, thu_tu ASC
        ) AS tep
        WHERE tai_lieu.id = tep.tai_lieu_id
    """)

    op.drop_index(op.f('ix_tep_tai_lieu_tai_lieu_id'), table_name='tep_tai_lieu')
    op.drop_table('tep_tai_lieu')
    # ### end Alembic commands ###
