"""Them cot trang_thai_xu_ly vao tai_lieu

Revision ID: e0b4cbae184f
Revises: 004cec467c98
Create Date: 2026-07-21 09:24:38.651237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b4cbae184f'
down_revision = '004cec467c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tai_lieu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trang_thai_xu_ly', sa.String(length=20), nullable=False, server_default='hoan_thanh'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tai_lieu', schema=None) as batch_op:
        batch_op.drop_column('trang_thai_xu_ly')

    # ### end Alembic commands ###
